"use client"
import { CacheProvider } from '@chakra-ui/next-js'
// import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ChakraProvider, ColorModeScript, Heading, IconButton, ThemeConfig, VStack, extendTheme, useColorMode, useColorModeValue } from '@chakra-ui/react'
import { Provider } from 'jotai'
import { BsSun, BsMoon } from "react-icons/bs";


// const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children, }: { children: React.ReactNode }) {
  const { toggleColorMode } = useColorMode();
  return (
    <html lang="en">
      <body className={inter.className}>
        <CustomProviders>
          {children}
        </CustomProviders>
      </body>
    </html>
  )
}
function CustomProviders({ children }: { children: React.ReactNode }) {
  return (
    <Provider>
      <CacheProvider>
        <ChakraProvider >
          {children}
        </ChakraProvider>
      </CacheProvider>
    </Provider>
  )
}
